# Generated by Django 4.0.3 on 2024-03-01 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_testsuitename_test_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuitename',
            name='ip_address',
            field=models.GenericIPAddressField(default=2, verbose_name='IP Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='max_dialect',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Dialect should be in the format 'DIALECT_SMB3_1_1'", regex='^[A-Za-z]+_[A-Za-z0-9_]+$')], verbose_name='Max Dialect'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='min_dialect',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Dialect should be in the format 'DIALECT_SMB3_1_1'", regex='^[A-Za-z]+_[A-Za-z0-9_]+$')], verbose_name='Min Dialect'),
        ),
    ]
