# Generated by Django 4.0.3 on 2024-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_testsuitename_ip_address_alter_testsuite_max_dialect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuitename',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP Address'),
        ),
    ]
